# Generated by Django 4.2.23 on 2025-09-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='expected_budget',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='similar_websites',
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
