# Generated by Django 4.2.23 on 2025-09-04 18:08

import consultations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='share_id',
            field=models.CharField(default=consultations.models.generate_uuid16, editable=False, max_length=16, unique=True),
        ),
    ]
