# Generated by Django 4.2.23 on 2025-09-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_share_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-created_at']},
        ),
    ]
