# Generated by Django 4.2.23 on 2025-09-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicinfo',
            name='clinic_info',
            field=models.TextField(null=True),
        ),
    ]
