# Generated by Django 4.2.23 on 2025-09-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcuts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='ico',
            field=models.CharField(choices=[('fa-heart', 'Heart'), ('fa-star', 'Star'), ('fa-user', 'User'), ('fa-check', 'Check'), ('fa-bell', 'Bell')], max_length=50),
        ),
    ]
