# Generated by Django 4.2.23 on 2025-09-04 12:47

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shortcuts', '0002_alter_shortcut_ico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortcut',
            name='text',
        ),
        migrations.AddField(
            model_name='shortcut',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='code',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='ico',
            field=models.CharField(choices=[('bi-heart', '❤️ Heart'), ('bi-stethoscope', '🩺 Stethoscope'), ('bi-thermometer', '🌡️ Thermometer'), ('bi-patch-check', '🩹 Bandage / Check'), ('bi-prescription', '💊 Prescription / Medicine'), ('bi-hospital', '🏥 Hospital'), ('bi-activity', '📈 Vital Signs'), ('bi-clipboard', '📋 Medical Record'), ('bi-person-heart', '🫀 Patient / Heart'), ('bi-droplet', '💧 Blood / Fluid'), ('bi-virus', '🦠 Virus / Infection'), ('bi-briefcase-medical', '💼 Medical Case'), ('bi-eye', '👁️ Eye / Vision'), ('bi-ear', '👂 Ear / Hearing'), ('bi-tooth', '🦷 Tooth / Dental'), ('bi-x-circle', '❌ Alert / Critical'), ('bi-check-circle', '✅ Normal / OK'), ('bi-calendar-check', '📅 Appointment'), ('bi-hospital-heart', '❤️🏥 Cardiology'), ('bi-hospital-fill', '🏥 Hospital / Clinic'), ('bi-pills', '💊 Pills / Medication'), ('bi-bandaid-fill', '🩹 Bandage / First Aid'), ('bi-bug', '🐛 Infection / Germ'), ('bi-heart-pulse', '💓 Heartbeat / Cardiac'), ('bi-thermometer-half', '🌡️ Temperature'), ('bi-journal-medical', '📓 Medical Journal / Notes'), ('bi-briefcase', '💼 Doctor / Case Files'), ('bi-person-bounding-box', '🧑\u200d⚕️ Doctor / Staff'), ('bi-blood', '🩸 Blood / Test'), ('bi-mortarboard', '🎓 Education / Certification'), ('bi-hospital-symbol', '⚕️ Health / Medical Symbol'), ('bi-vial', '🧪 Laboratory / Test Tube'), ('bi-activity', '📊 Health Statistics'), ('bi-file-medical', '📄 Medical File'), ('bi-hospital-door', '🚪 Hospital / Clinic Entry'), ('bi-clipboard-data', '📋 Patient Data'), ('bi-needle', '💉 Injection / Vaccine'), ('bi-person-plus', '➕ New Patient'), ('bi-person-dash', '➖ Discharge / Remove Patient'), ('bi-heart-fill', '❤️ Heart / Vital'), ('bi-gem', '💎 Specialty / Highlight'), ('bi-globe', '🌍 Global Health'), ('bi-lightning-charge', '⚡ Emergency / Critical'), ('bi-watch', '⌚ Monitoring / Time'), ('bi-shield-check', '🛡️ Protection / Immunity'), ('bi-star', '⭐ Important / Priority')], max_length=50),
        ),
    ]
